export interface FAQ { q: string; a: string }

export const postFaqs: Record<string, FAQ[]> = {
  "n8n-vs-zapier-vs-make-2026": [
    { q: "Which is cheaper — n8n, Zapier, or Make.com?", a: "n8n is the cheapest long-term. Self-hosted n8n costs only your server fees (~$5–$10/month VPS). Make.com is the best value among cloud platforms, charging per operation rather than per task like Zapier. Zapier becomes expensive quickly at scale — a workflow running 5,000 times a month can cost 20× more on Zapier than on Make or n8n." },
    { q: "Is n8n better than Zapier for technical teams?", a: "Yes, for teams with any technical capacity. n8n supports custom JavaScript/Python in any node, self-hosting for unlimited workflows, complex branching, and native AI integrations (OpenAI, Claude, LangChain, vector DBs). Zapier is simpler and better for non-technical users who need straightforward, low-volume automations live in minutes." },
    { q: "What is the difference between n8n and Make.com?", a: "n8n is open-source, developer-friendly, and supports self-hosting with no per-execution pricing. Make.com (formerly Integromat) is a visual, cloud-only platform with a generous free plan and competitive operation-based pricing. n8n suits technical teams; Make.com suits business users who want power without managing servers." },
    { q: "Which automation platform is best for Indian small businesses?", a: "Make.com and n8n offer the best value for Indian businesses. Make.com's operation-based pricing is more predictable than Zapier's task model. n8n's self-hosted option eliminates recurring costs entirely — ideal for businesses running high-volume automations or AI-heavy workflows. Zapier is best reserved for ultra-simple, low-volume use cases." },
    { q: "Can I migrate from Zapier to n8n or Make without losing my automations?", a: "Yes. Most Zapier automations can be rebuilt in Make or n8n in a fraction of the original setup time. The logic transfers directly — triggers, actions, and filters map to equivalents on both platforms. HowAutomate handles Zapier-to-n8n and Zapier-to-Make migrations for clients, typically with a 70–85% reduction in monthly automation costs." },
  ],
  "ai-receptionist-guide": [
    { q: "How much does an AI receptionist cost in India?", a: "An AI receptionist in India typically costs ₹4,000–₹12,000 per month depending on call volume and integration complexity, compared to ₹20,000–₹35,000 per month for a full-time human receptionist. Most businesses recover the implementation cost within 6–10 weeks through staff time savings and improved lead capture." },
    { q: "Can an AI receptionist handle calls in Hindi?", a: "Yes. Modern AI receptionists can be configured for Hindi, English, and regional Indian languages. The voice model is fine-tuned on your specific business vocabulary and can switch languages mid-conversation based on the caller's preference." },
    { q: "How long does it take to set up an AI receptionist?", a: "A standard AI receptionist deployment takes 2–4 weeks: approximately 1 week for knowledge base setup and voice configuration, 1 week for calendar and CRM integration and testing, and 1–2 weeks of parallel operation before going fully live." },
    { q: "What happens when the AI cannot handle a call?", a: "When the AI encounters a query outside its knowledge base or a complex complaint, it seamlessly escalates to a human staff member via call transfer, WhatsApp notification, or email alert — so no caller is ever left without a response." },
    { q: "Which industries benefit most from AI receptionists?", a: "Medical and dental clinics, law firms, real estate agencies, coaching institutes, salons, and any service business receiving more than 20 inbound calls per day see the strongest ROI. The typical payback period is 6–10 weeks, with 75–85% of calls handled fully by the AI without human involvement." },
  ],
  "crm-automation-small-business": [
    { q: "What CRM is best for small business automation in India?", a: "Zoho CRM is the most popular choice for Indian small businesses — strong automation features, GST-friendly invoicing, WhatsApp integration, and pricing starting from ₹800/user/month. HubSpot's free CRM is ideal for businesses just starting. Pipedrive suits sales-focused teams who want a simple pipeline view." },
    { q: "How much does CRM automation cost to implement?", a: "Basic CRM automation — lead capture, email sequences, and task automation — costs ₹15,000–₹50,000 to implement and takes 2–4 weeks. Advanced systems with AI lead scoring, multi-channel integration, and custom dashboards range from ₹50,000–₹2,00,000 depending on complexity and the number of integrations required." },
    { q: "Can CRM automation work with WhatsApp Business?", a: "Yes. Modern CRM systems integrate with WhatsApp Business API to capture leads from WhatsApp, send automated follow-up messages, and log all interactions in your CRM. This is particularly effective for Indian businesses where WhatsApp is the primary communication channel for sales and support." },
    { q: "How long does CRM automation take to pay for itself?", a: "Most businesses see ROI within 60–90 days. The main drivers are: 60–80% reduction in manual data entry time, 25–40% improvement in lead-to-customer conversion rate, and the ability for one salesperson to manage 2–3× more leads than before." },
    { q: "What is the difference between CRM automation and a marketing automation platform?", a: "CRM automation focuses on managing the sales pipeline — lead capture, follow-up, deal stages, and task assignment. Marketing automation focuses on top-of-funnel activities — email campaigns, lead scoring, and nurture sequences. Modern platforms like HubSpot and Zoho combine both, but dedicated tools like Mailchimp or ActiveCampaign handle marketing automation separately from your CRM." },
  ],
  "whatsapp-business-ai-automation": [
    { q: "How do I get access to WhatsApp Business API in India?", a: "You need to apply through a Meta-approved Business Solution Provider (BSP) such as AiSensy, Wati, Gupshup, 360dialog, or Twilio. You'll need a verified Facebook Business Manager account, a dedicated phone number, and business verification. Approval typically takes 3–7 business days." },
    { q: "What is the cost of WhatsApp Business API in India?", a: "WhatsApp charges per conversation (24-hour window), not per message. Rates in India are approximately ₹0.30–₹1.50 per conversation depending on type (service, utility, marketing, or authentication). BSP platform fees add ₹2,000–₹10,000/month depending on volume and features." },
    { q: "Can WhatsApp bots handle payments and bookings?", a: "Yes. WhatsApp AI agents can send Razorpay or PayU payment links, confirm payments via webhook, and book appointments directly into Google Calendar or Calendly. The bot handles the entire flow end-to-end — from enquiry to payment confirmation — without human intervention." },
    { q: "What is the 24-hour rule on WhatsApp Business?", a: "WhatsApp allows free-form messages only within a 24-hour window after the customer last messaged you. Outside that window, you must use pre-approved Message Templates and pay a per-conversation fee. Sending unsolicited messages outside this window can result in your number being rate-limited or banned." },
    { q: "How many support tickets can a WhatsApp AI agent handle?", a: "A well-built WhatsApp AI agent typically resolves 80–92% of support tickets end-to-end without human involvement — covering order tracking, FAQs, appointment booking, returns, and basic troubleshooting. The remaining 8–20% requiring human judgment are automatically escalated to a live agent." },
  ],
  "voice-ai-agents-outbound-sales": [
    { q: "What is the cost per call for a voice AI sales agent?", a: "Typical all-in cost is $0.08–$0.12 per minute of conversation. A 4-minute qualification call costs roughly $0.40–$0.50, versus $8–$15 per call for a human SDR fully loaded. At scale (10,000+ calls per month), voice AI outbound costs 15–30× less than an equivalent human team." },
    { q: "Which voice AI platforms are best for outbound sales?", a: "The leading platforms for outbound voice AI in 2026 are Vapi, Bland AI, and Retell AI for the voice layer, combined with ElevenLabs or OpenAI Realtime for voice synthesis, and Twilio or Telnyx for telephony. For enterprise deployments, custom OpenAI Realtime + ElevenLabs setups offer the most control." },
    { q: "Is voice AI for cold calling legal in India?", a: "Yes, with proper compliance. Under TRAI guidelines, you must register with the Distributed Ledger Technology (DLT) system, use only approved message templates for promotional calls, and maintain an opt-out mechanism. Commercial calls must identify the calling business and purpose. Always disclose that the caller is an AI agent when asked." },
    { q: "Can voice AI agents handle objections during sales calls?", a: "Yes, for common objections. Voice AI agents can be trained with objection-handling scripts — 'too expensive', 'not the right time', 'send me more info' — and respond naturally. However, complex enterprise objections or multi-stakeholder negotiations still require human judgment. The current best practice is AI handles qualification and initial discovery; humans close." },
    { q: "How long does it take to deploy a voice AI sales agent?", a: "Most clients go live within 14–21 days. Week 1: script design, knowledge base, and voice selection. Week 2: telephony setup, CRM integration, calendar booking connection, and compliance review. Week 3: test calls and parallel deployment. Break-even on implementation cost is typically within 60 days." },
  ],
  "deepseek-vs-chatgpt-vs-claude-business": [
    { q: "Is DeepSeek cheaper than ChatGPT for business use?", a: "Yes, significantly. DeepSeek V3 costs $0.27/$1.10 per million input/output tokens versus GPT-4o at $2.50/$10.00 — roughly 10× cheaper for equivalent general-purpose tasks. For high-volume automation workloads like classification, extraction, and content generation, DeepSeek and Gemini 2.0 Flash offer the best cost-efficiency in 2026." },
    { q: "Which LLM is best for business automation in 2026?", a: "There is no single best model — the optimal choice depends on your workload. GPT-4o is best for complex tool-calling and agent workflows. Claude 3.7 Sonnet leads on reasoning and long-form writing. Gemini 2.0 Flash is fastest with the largest context window for document processing. DeepSeek V3 offers the best price-to-quality ratio for high-volume classification and content generation." },
    { q: "Can DeepSeek be self-hosted for data privacy?", a: "Yes. DeepSeek R1 is fully open-source with model weights available for self-hosting. You can run it on your own GPU servers or cloud infrastructure, keeping all data within your environment. This makes it suitable for healthcare, finance, and legal applications with strict data residency requirements." },
    { q: "What is the difference between Claude and ChatGPT for coding?", a: "Both are strong coding models, but Claude 3.7 Sonnet has overtaken GPT-4o on most coding benchmarks as of 2026, particularly for complex reasoning tasks, debugging, and multi-file code generation. GPT-4o maintains an edge in tool-calling reliability and ecosystem integrations. For most coding automation use cases, either model works well." },
    { q: "Should I use one LLM or a mix of models for my business?", a: "A multi-model architecture is increasingly the best practice for cost-efficiency. Use fast, cheap models (Gemini 2.0 Flash, DeepSeek V3) for high-volume classification and extraction. Use mid-tier models (Claude Haiku, GPT-4o-mini) for conversational layers. Reserve premium models (Claude 3.7 Sonnet, GPT-4o) for complex reasoning and agent orchestration. This approach typically cuts LLM costs by 60–80% without sacrificing quality." },
  ],
  "marketing-ai-agent-2026": [
    { q: "What is a marketing AI agent?", a: "A marketing AI agent is an autonomous system that handles specific marketing tasks — content creation, ad optimisation, email nurturing, lead scoring — with minimal human oversight. Unlike simple automation that executes predefined rules, an AI agent reasons, adapts, and improves based on real-time outcomes and signals from your marketing platforms." },
    { q: "How much does a marketing AI agent cost to build?", a: "A basic marketing AI agent (content generation + ad monitoring) costs ₹30,000–₹80,000 to build and typically ₹5,000–₹15,000/month in platform and API costs. A full-stack marketing AI agent (content, ads, lead nurturing, CRM integration) costs ₹1,00,000–₹3,00,000 to implement. Most clients achieve positive ROI within 60–90 days." },
    { q: "Can AI replace my marketing team?", a: "AI agents replace specific tasks, not your team. They handle volume work — content drafts, bid adjustments, A/B test execution, lead scoring — freeing your team to focus on strategy, brand decisions, and creative direction. Businesses that see the best results treat AI agents as team members that need onboarding and ongoing direction, not set-it-and-forget-it tools." },
    { q: "Which marketing tasks are best automated with AI in 2026?", a: "The highest-ROI marketing automations are: social media content generation and scheduling, PPC bid management and keyword harvesting, personalised email sequence management, lead scoring from engagement signals, SEO content briefs and first drafts, and competitive monitoring. These tasks are well-defined enough for AI to execute reliably with minimal human review after the first few weeks." },
    { q: "How long does it take to see results from a marketing AI agent?", a: "Most clients see measurable results within 30–60 days. Content output typically increases 5–10× in the first month. Ad campaign ROAS improvements of 20–40% are common by week 6 as the agent optimises based on conversion data. Lead quality and conversion rates take 60–90 days to show full impact as the nurture sequences gather enough data to personalise effectively." },
  ],
  "what-is-etl": [
    { q: "What does ETL stand for?", a: "ETL stands for Extract, Transform, Load — the three stages of moving data from source systems to a destination like a data warehouse. Extract pulls raw data from databases, APIs, or files. Transform cleans, deduplicates, and reshapes it. Load writes the processed data to its final destination for analysis and reporting." },
    { q: "What is the difference between ETL and ELT?", a: "In traditional ETL, data is transformed in a staging area before loading into the warehouse. In modern ELT (Extract, Load, Transform), raw data is loaded first into cloud warehouses like BigQuery or Snowflake, then transformed using SQL and tools like dbt. ELT is now the standard for cloud-native architectures because modern warehouses can transform data faster than external staging." },
    { q: "What are the most common ETL tools?", a: "Popular ETL tools include Apache Airflow and Prefect for orchestration, dbt for SQL-based transformations, Fivetran and Airbyte for managed source connectors, Azure Data Factory for Microsoft-stack environments, and AWS Glue for AWS-native workloads. Python with pandas and SQLAlchemy is widely used for custom pipeline development." },
    { q: "How often should ETL pipelines run?", a: "It depends on business needs. Daily batch ETL is appropriate for most BI and reporting use cases. Hourly runs suit operational dashboards. Real-time streaming ETL (using Kafka or Kinesis) is reserved for use cases requiring up-to-the-minute data like fraud detection or live inventory tracking. Most businesses start with daily batch and add real-time layers only when the business case justifies the added complexity." },
    { q: "What is ETL used for in small businesses?", a: "Small businesses use ETL pipelines to consolidate data from multiple tools (CRM, accounting, e-commerce platform) into a single reporting database or spreadsheet. Common use cases include unified sales reporting, automated P&L dashboards, inventory tracking, and customer behaviour analytics — replacing hours of manual data copying with fully automated, scheduled data flows." },
  ],
}
